trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYPI_CACHE: $(Pipeline.Workspace)/.pypi

stages:
- stage: CC_CVRP_Stage
  displayName: 'CC-CVRP Stage'
  jobs:
  - job: InstallDependencies
    displayName: 'Install Dependencies'
    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        cd CC-CVRP
        python -m pip install --upgrade pip
        pip install --upgrade wheel
        pip install --cache-dir $(PYPI_CACHE) -r requirements.txt
      displayName: 'Install Python Dependencies'

  - job: RunCCPInput
    displayName: 'Run ccp_input.py'
    steps:
    - checkout: self

    - script: |
        cd CC-CVRP
        python ccp_input.py
      displayName: 'Run ccp_input.py'
