trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'


stages:

- stage: InstallDependencies
  displayName: 'Install Dependencies'
  jobs:
  - job: InstallDependenciesJob
    displayName: 'Install Dependencies Job'
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11.6'  # Replace with your Python version
        addToPath: true
        
    - script: |
        cd CC-CVRP
        python -m pip install -r requirements.txt
      displayName: 'Install Dependencies'

- stage: CC_CVRP_Stage
  displayName: 'CC-CVRP Stage'
  jobs:
  - job: RunCCPInput
    displayName: 'Run ccp_input.py'
    steps:
    - checkout: self

    - script: |
        cd CC-CVRP
        python -m pip install -r requirements.txt 
        python ccp_input.py
      displayName: 'Run ccp_input.py'

- stage: RunCCP
  displayName: 'Run CCP.py Stage'
  jobs:
  - job: RunCCPFile
    displayName: 'Run CCP.py'
    steps:
    
    - checkout: self

    - script: |
        cd CC-CVRP
        python CCP.py
      displayName: 'Run CCP.py'
